### ISSUE TITLE
Missing files in one folder

### ISSUE THREAD

**Issue by andrewlee94** [CCSI-Toolset/bfb_reactor#10]
One of the subfolders is missing the .gPj file for the BFB model. This is the actual file containing the model information, so this needs to be fixed.

bfb_reactor/BFB_gPROMS/REGENERATOR/OVERFLOWTYPE/DYNAMIC/SINGLE-STAGE/

The .bak file was also missing, but this is not needed, and all the other .bak files are in the process of being deleted.

**Comment by andrewlee94** [comment]
@ksbeattie  You copied the right thing - I did a manual diff in Excel and there were no differences. I also checked the gSTORE file, and it is up to date, so there should be no problems there.

**Comment by ksbeattie** [comment]
Thanks!  I optimistically cut the release hoping that would be your answer.
